title: Pindograma
email: redacao@pindograma.com.br
description: Jornalismo de dados sem papo-furado.
baseurl: ""
url: "https://pindograma.com.br"
github_username: pindograma
lang: pt_BR

twitter:
  username: pindograma
  card: summary_large_image

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

  - scope:
      path: ""
      type: "pages"
    values:
      image: "/assets/images/default-cover.png"

tag_page_layout: section
tag_page_dir: section
